# Generated by Django 4.2.1 on 2023-05-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category_content',
            field=models.CharField(choices=[('LAYANAN_IMIGRASI', 'LAYANAN_IMIGRASI'), ('STANDAR', 'STANDAR')], default='STANDAR', max_length=50),
        ),
    ]
