# Generated by Django 4.2.1 on 2023-05-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_filearsipdandokumen_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kakanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('masa_jabatan', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='kakanim/')),
            ],
        ),
        migrations.CreateModel(
            name='StrukturOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jabatan', models.CharField(choices=[('KEPALA_KANTOR', 'KEPALA_KANTOR'), ('KASUBAG_TATA_USAHA', 'KASUBAG_TATA_USAHA'), ('KASI_LALU_LINTAS_DAN_IZIN_TINGGAL_KEIMIGRASIAN', 'KASI_LALU_LINTAS_DAN_IZIN_TINGGAL_KEIMIGRASIAN'), ('KASI_TEKNOLOGI_DAN_INFORMASI_KEIMIGRASIAN', 'KASI_TEKNOLOGI_DAN_INFORMASI_KEIMIGRASIAN'), ('KASI_INTELEJEN_DAN_PENINDAKAN_KEIMIGRASIAN', 'KASI_INTELEJEN_DAN_PENINDAKAN_KEIMIGRASIAN'), ('KAUR_KEPEGAWAIAN', 'KAUR_KEPEGAWAIAN'), ('KASUBSI_LALU_LINTAS_KEIMIGRASIAN', 'KASUBI_LALU_LINTAS_KEIMIGRASIAN'), ('KASUBSI_IZIN_TINGGAL_KEIMIGRASIAN', 'KASUBI_IZIN_TINGGAL_KEIMIGRASIAN'), ('KASUBSI_TEKNOLOGI_INFORMASI_KEIMIGRASIAN', 'KASUBSI_TEKNOLOGI_INFORMASI_KEIMIGRASIAN')], max_length=100)),
                ('TMT', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='filearsipdandokumen',
            name='category',
            field=models.CharField(choices=[('DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN', 'DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN'), ('LAPORAN_AKUNTABILITAS_KINERJA', 'LAPORAN_AKUNTABILITAS_KINERJA')], max_length=50),
        ),
    ]
