# Generated by Django 4.2.1 on 2023-05-30 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_content_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotogaleri',
            name='foto_category',
            field=models.CharField(choices=[('DOKUMENTASI', 'DOKUMENTASI'), ('STANDAR', 'STANDAR')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filearsipdandokumen',
            name='category',
            field=models.CharField(choices=[('INFORMASI_BERKALA', 'INFORMASI_BERKALA'), ('DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN', 'DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN'), ('TIMPORA', 'TIMPORA'), ('LAPORAN_AKUNTABILITAS_KINERJA', 'LAPORAN_AKUNTABILITAS_KINERJA')], max_length=50),
        ),
    ]
