# Generated by Django 4.2.1 on 2023-05-30 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_fotogaleri_foto_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='youtube_category',
            field=models.CharField(choices=[('ZONA_INTEGRITAS', 'ZONA_INTEGRITAS'), ('STANDAR', 'STANDAR')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
