# Generated by Django 4.2.1 on 2023-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_youtubevideo_youtube_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filearsipdandokumen',
            name='category',
            field=models.CharField(choices=[('LAPORAN_AKUNTABILITAS_KINERJA', 'LAPORAN_AKUNTABILITAS_KINERJA'), ('DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN', 'DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN'), ('INFORMASI_BERKALA', 'INFORMASI_BERKALA'), ('TIMPORA', 'TIMPORA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_category',
            field=models.CharField(choices=[('ZONA_INTEGRITAS', 'ZONA_INTEGRITAS'), ('JINGLE', 'JINGLE'), ('STANDAR', 'STANDAR')], max_length=50),
        ),
    ]
