# Generated by Django 4.2.1 on 2023-06-04 08:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_visidanmisi_alter_filearsipdandokumen_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filearsipdandokumen',
            name='category',
            field=models.CharField(choices=[('INFORMASI_BERKALA', 'INFORMASI_BERKALA'), ('DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN', 'DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN'), ('TIMPORA', 'TIMPORA'), ('LAPORAN_AKUNTABILITAS_KINERJA', 'LAPORAN_AKUNTABILITAS_KINERJA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='strukturorganisasi',
            name='jabatan',
            field=models.CharField(choices=[('KEPALA_KANTOR', 'KEPALA_KANTOR'), ('KASUBAG_TATA_USAHA', 'KASUBAG_TATA_USAHA'), ('KASI_LALU_LINTAS_DAN_IZIN_TINGGAL_KEIMIGRASIAN', 'KASI_LALU_LINTAS_DAN_IZIN_TINGGAL_KEIMIGRASIAN'), ('KASI_TEKNOLOGI_DAN_INFORMASI_KEIMIGRASIAN', 'KASI_TEKNOLOGI_DAN_INFORMASI_KEIMIGRASIAN'), ('KASI_INTELEJEN_DAN_PENINDAKAN_KEIMIGRASIAN', 'KASI_INTELEJEN_DAN_PENINDAKAN_KEIMIGRASIAN'), ('KAUR_KEPEGAWAIAN', 'KAUR_KEPEGAWAIAN'), ('KASUBSI_LALU_LINTAS_KEIMIGRASIAN', 'KASUBI_LALU_LINTAS_KEIMIGRASIAN'), ('KASUBSI_IZIN_TINGGAL_KEIMIGRASIAN', 'KASUBI_IZIN_TINGGAL_KEIMIGRASIAN'), ('KASUBSI_TEKNOLOGI_INFORMASI_KEIMIGRASIAN', 'KASUBSI_TEKNOLOGI_INFORMASI_KEIMIGRASIAN'), ('KASUBSI_INFORMASI_DAN_KOMUNIKASI_KEIMIGRASIAN', 'KASUBSI_INFORMASI_DAN_KOMUNIKASI_KEIMIGRASIAN'), ('KASUBSI_INTELIJEN_KEIMIGRASIAN', 'KASUBSI_INTELIJEN_KEIMIGRASIAN'), ('KASUBSI_PENINDAKAN_KEIMIGRASIAN', 'KASUBSI_PENINDAKAN_KEIMIGRASIAN')], max_length=100),
        ),
        migrations.AlterField(
            model_name='visidanmisi',
            name='misi',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
