# Generated by Django 4.2.1 on 2023-06-04 20:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_filearsipdandokumen_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPerusahaanDanPenginapanWilayahKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilayah_kerja', models.CharField(choices=[('BOJONEGARA', 'BOJONEGARA'), ('CIBEBER', 'CIBEBER'), ('CILEGON', 'CILEGON'), ('CITANGKIL', 'CITANGKIL'), ('CIWANDAN', 'CIWANDAN'), ('GEROGOL', 'GEROGOL'), ('JOMBANG', 'JOMBANG'), ('PULOAMPEL', 'PULOAMPEL'), ('PULOMERAK', 'PULOMERAK'), ('PURWAKARTA', 'PURWAKARTA')], max_length=20)),
                ('list_of_perusahaan_penginapan', ckeditor_uploader.fields.RichTextUploadingField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='filearsipdandokumen',
            name='category',
            field=models.CharField(choices=[('INFORMASI_BERKALA', 'INFORMASI_BERKALA'), ('LAPORAN_AKUNTABILITAS_KINERJA', 'LAPORAN_AKUNTABILITAS_KINERJA'), ('TIMPORA', 'TIMPORA'), ('DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN', 'DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN')], max_length=50),
        ),
    ]
