# Generated by Django 4.2.5 on 2023-11-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_listperusahaandanpenginapanwilayahkerja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexKepuasanMasyarakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_sangat_baik', models.IntegerField()),
                ('total_baik', models.IntegerField()),
                ('total_kurang_baik', models.IntegerField()),
                ('total_tidak_baik', models.IntegerField()),
                ('p', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPersepsiKorupsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_sangat_baik', models.IntegerField()),
                ('total_baik', models.IntegerField()),
                ('total_kurang_baik', models.IntegerField()),
                ('total_tidak_baik', models.IntegerField()),
                ('p', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='IndexSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sangat_baik', models.IntegerField(default=1)),
                ('total_baik', models.IntegerField(default=1)),
                ('total_kurang_baik', models.IntegerField(default=1)),
                ('total_tidak_baik', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LaporanPelayananWNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_ijin_tinggal_kunjungan', models.IntegerField()),
                ('total_izin_tinggal_terbatas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LaporanPelayananWNI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_paspor_baru', models.IntegerField()),
                ('total_pergantian_paspor', models.IntegerField()),
                ('total_pergantian_paspor_hilang_rusak', models.IntegerField()),
                ('total_penyerahan_paspor', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='strukturorganisasi',
            name='foto',
            field=models.ImageField(default='1', upload_to='photo_pejabat/'),
        ),
        migrations.AlterField(
            model_name='filearsipdandokumen',
            name='category',
            field=models.CharField(choices=[('INFORMASI_BERKALA', 'INFORMASI_BERKALA'), ('DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN', 'DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN'), ('TIMPORA', 'TIMPORA'), ('LAPORAN_AKUNTABILITAS_KINERJA', 'LAPORAN_AKUNTABILITAS_KINERJA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='strukturorganisasi',
            name='jabatan',
            field=models.CharField(choices=[('KEPALA_KANTOR', 'KEPALA_KANTOR'), ('KASUBAG_TATA_USAHA', 'KASUBAG_TATA_USAHA'), ('KASI_LALU_LINTAS_DAN_IZIN_TINGGAL_KEIMIGRASIAN', 'KASI_LALU_LINTAS_DAN_IZIN_TINGGAL_KEIMIGRASIAN'), ('KASI_TEKNOLOGI_DAN_INFORMASI_KEIMIGRASIAN', 'KASI_TEKNOLOGI_DAN_INFORMASI_KEIMIGRASIAN'), ('KASI_INTELEJEN_DAN_PENINDAKAN_KEIMIGRASIAN', 'KASI_INTELEJEN_DAN_PENINDAKAN_KEIMIGRASIAN'), ('KAUR_KEPEGAWAIAN', 'KAUR_KEPEGAWAIAN'), ('KASUBSI_LALU_LINTAS_KEIMIGRASIAN', 'KASUBI_LALU_LINTAS_KEIMIGRASIAN'), ('KASUBSI_IZIN_TINGGAL_KEIMIGRASIAN', 'KASUBSI_IZIN_TINGGAL_KEIMIGRASIAN'), ('KASUBSI_TEKNOLOGI_INFORMASI_KEIMIGRASIAN', 'KASUBSI_TEKNOLOGI_INFORMASI_KEIMIGRASIAN'), ('KASUBSI_INFORMASI_DAN_KOMUNIKASI_KEIMIGRASIAN', 'KASUBSI_INFORMASI_DAN_KOMUNIKASI_KEIMIGRASIAN'), ('KASUBSI_INTELIJEN_KEIMIGRASIAN', 'KASUBSI_INTELIJEN_KEIMIGRASIAN'), ('KASUBSI_PENINDAKAN_KEIMIGRASIAN', 'KASUBSI_PENINDAKAN_KEIMIGRASIAN')], max_length=100),
        ),
        migrations.CreateModel(
            name='IPKandIKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('calo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calo', to='main.indexsurvey')),
                ('diskriminasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diskriminasi', to='main.indexsurvey')),
                ('gratifikasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratifikasi', to='main.indexsurvey')),
                ('informasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informasi', to='main.indexsurvey')),
                ('kecurangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kecurangan', to='main.indexsurvey')),
                ('konsultasi_dan_pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konsultasi_dan_pengaduan', to='main.indexsurvey')),
                ('persyaratan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persyaratan', to='main.indexsurvey')),
                ('prosedur_atau_alur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosedur_atau_alur', to='main.indexsurvey')),
                ('pungli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pungli', to='main.indexsurvey')),
                ('respon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respon', to='main.indexsurvey')),
                ('sarana_prasarana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sarana_prasarana', to='main.indexsurvey')),
                ('tarif_biaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarif_biaya', to='main.indexsurvey')),
                ('waktu_penyelesaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waktu_penyelesaian', to='main.indexsurvey')),
            ],
        ),
    ]
