# Generated by Django 4.2.5 on 2023-11-01 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_indexkepuasanmasyarakat_indexpersepsikorupsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filearsipdandokumen',
            name='category',
            field=models.CharField(choices=[('LAPORAN_AKUNTABILITAS_KINERJA', 'LAPORAN_AKUNTABILITAS_KINERJA'), ('TIMPORA', 'TIMPORA'), ('DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN', 'DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN'), ('INFORMASI_BERKALA', 'INFORMASI_BERKALA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ipkandikm',
            name='calo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calo', to='main.indexsurvey'),
        ),
        migrations.AlterField(
            model_name='ipkandikm',
            name='diskriminasi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diskriminasi', to='main.indexsurvey'),
        ),
        migrations.AlterField(
            model_name='ipkandikm',
            name='gratifikasi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gratifikasi', to='main.indexsurvey'),
        ),
        migrations.AlterField(
            model_name='ipkandikm',
            name='informasi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informasi', to='main.indexsurvey'),
        ),
        migrations.AlterField(
            model_name='ipkandikm',
            name='kecurangan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kecurangan', to='main.indexsurvey'),
        ),
        migrations.AlterField(
            model_name='ipkandikm',
            name='konsultasi_dan_pengaduan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='konsultasi_dan_pengaduan', to='main.indexsurvey'),
        ),
        migrations.AlterField(
            model_name='ipkandikm',
            name='persyaratan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persyaratan', to='main.indexsurvey'),
        ),
        migrations.AlterField(
            model_name='ipkandikm',
            name='prosedur_atau_alur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prosedur_atau_alur', to='main.indexsurvey'),
        ),
        migrations.AlterField(
            model_name='ipkandikm',
            name='pungli',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pungli', to='main.indexsurvey'),
        ),
        migrations.AlterField(
            model_name='ipkandikm',
            name='respon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respon', to='main.indexsurvey'),
        ),
        migrations.AlterField(
            model_name='ipkandikm',
            name='sarana_prasarana',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sarana_prasarana', to='main.indexsurvey'),
        ),
        migrations.AlterField(
            model_name='ipkandikm',
            name='tarif_biaya',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarif_biaya', to='main.indexsurvey'),
        ),
        migrations.AlterField(
            model_name='ipkandikm',
            name='waktu_penyelesaian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waktu_penyelesaian', to='main.indexsurvey'),
        ),
    ]
