# Generated by Django 4.2.5 on 2023-11-01 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_filearsipdandokumen_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexsurvey',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexsurvey',
            name='variable',
            field=models.CharField(choices=[('INFORMASION', 'informasi'), ('PERSYARATAN', 'persyaratan'), ('PROSEDUR_ATAU_ALUR', 'prosedur_atau_alur'), ('WAKTU_PENYELESAIAN', 'waktu_penyelesaian'), ('TARIF_BIAYA', 'tarif_biaya'), ('SARANA_PRASARANA', 'sarana_prasarana'), ('RESPON', 'respon'), ('KONSULTASI_DAN_PENGADUAN', 'konsultasi_dan_pengaduan'), ('DISKRIMINASI', 'diskriminasi'), ('KECURANGAN', 'kecurangan'), ('GRATIFIKASI', 'gratifikasi'), ('PUNGLI', 'pungli'), ('CALO', 'calo')], default='CALO', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filearsipdandokumen',
            name='category',
            field=models.CharField(choices=[('TIMPORA', 'TIMPORA'), ('DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN', 'DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN'), ('INFORMASI_BERKALA', 'INFORMASI_BERKALA'), ('LAPORAN_AKUNTABILITAS_KINERJA', 'LAPORAN_AKUNTABILITAS_KINERJA')], max_length=50),
        ),
    ]
