# Generated by Django 4.2.5 on 2023-11-01 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_indexsurvey_date_indexsurvey_variable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filearsipdandokumen',
            name='category',
            field=models.CharField(choices=[('LAPORAN_AKUNTABILITAS_KINERJA', 'LAPORAN_AKUNTABILITAS_KINERJA'), ('INFORMASI_BERKALA', 'INFORMASI_BERKALA'), ('DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN', 'DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN'), ('TIMPORA', 'TIMPORA')], max_length=50),
        ),
        migrations.CreateModel(
            name='IPKandIKMSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('index_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.indexsurvey')),
            ],
        ),
    ]
