# Generated by Django 4.2.5 on 2023-11-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_filearsipdandokumen_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexsurvey',
            name='date',
        ),
        migrations.RemoveField(
            model_name='indexsurvey',
            name='variable',
        ),
        migrations.AlterField(
            model_name='filearsipdandokumen',
            name='category',
            field=models.CharField(choices=[('INFORMASI_BERKALA', 'INFORMASI_BERKALA'), ('LAPORAN_AKUNTABILITAS_KINERJA', 'LAPORAN_AKUNTABILITAS_KINERJA'), ('DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN', 'DAFTAR_ISIAN_PELAKSANAAN_ANGGARAN'), ('TIMPORA', 'TIMPORA')], max_length=50),
        ),
    ]
